### ISSUE TITLE
support "SectionNumberLevel"

### ISSUE THREAD

**Issue by mochimochiki** [mochimochiki/hugo-theme-vivliocli#14]
各記事は章、もしくは節としてPDF目次に表示されることが想定されている。この章節に通し番号を振りたい。

pdfconfigのある階層をルートとして、階層構造を解釈し、各記事のh1タイトルに1.2.2 などの通し番号を挿し込む。

‘config.toml‘でSectionNumberLevel=3なら3レベルまで、=0なら非表示（デフォルト非表示）

デリミタはSectionNumberDelimiter="."などで指定できるようにする（デフォルトはピリオド）

レベル1階層のみ、前後に文字列を挿入できるようにする。

第1章、Chapter 1、など。

※pdfconfigが複数階層に存在する場合は、最もルートに近い階層が優先される。

**Comment by mochimochiki** [comment]
番号についてはpdftocに関わらずレベル指定した見出しまですべて表示する。よってpdftocをまばらにつけると例えば目次には
1.2.1
1.2.3
1.2.4
のように歯抜けになってしまう場合もあるが、それは仕様とする。（tocにh2をすべて表示、などは現在のTableOfContentを元にしたtoc化は難しい）

**Comment by mochimochiki** [comment]
only_showIfs, flat_toc のときはサポートしない（レベル0）

**Comment by mochimochiki** [comment]
only_showIfs, flat_toc は一旦廃止した。

**Comment by mochimochiki** [comment]
最終的に以下のような仕様とした。

[config.toml]
```toml
sectionNumberLevel = 3 # 章・節番号を表示するレベル。0なら表示しない
sectionDelimiter = "-" # 章・節番号のデリミタ
sectionTopFormat = "Chapter %s" # トップレベルの章のフォーマット
```

* pdfconfigが存在していれば、そのディレクトリ下から章・節番号を振る
* pdfconfigが存在していなければ、章・節番号は振らない
* 章・節番号が振られる対象は「記事タイトル」「セクションタイトル」「記事ヘッダ h2/ h3」
* PDF目次に記事内のヘッダを表示するには`.pdftoc`クラスを付加する。（手動でも可）
* 記事タイトルに加え、h2/h3タグまではsectionNumberLevelで指定されているレベル内であれば章・節番号を付加し、`.pdftoc`も自動でつける（=PDF目次に出す）
* `.pdftoc`は記事のみ（セクションには対応しない）
